### ISSUE TITLE
Change Font in Contacts

### ISSUE THREAD

**Issue by msyugovich** [AshotN/GenYesGHS#1]
this text should be Roboto to match the text above it

www.gusd.net/site/Default.aspx?PageID=193
818-242-3161 x.577
Frank Schlueter, Director
fschlueter@gusd.net
Valerie Mitchell, Assistant Director
vmitchell@gusd.net
Kris Kohlmeier, Teacher Specialist
kkohlmeier@gusd.net
Peter Richter, Customer Support Technician
prichter@gusd.net

**Comment by AshotN** [comment]
Fixed in: https://github.com/AshotN/GenYesGHS/commit/15fc8b6e986719e25bd2d93f7e075a6be6243e10

**Comment by msyugovich** [comment]
I like this system.

On Wed, Mar 4, 2015 at 9:40 AM, Ashot Nazaryan notifications@github.com
wrote:

> Fixed in: 15fc8b6
> https://github.com/AshotN/GenYesGHS/commit/15fc8b6e986719e25bd2d93f7e075a6be6243e10
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/AshotN/GenYesGHS/issues/1#issuecomment-77206408.

## 

+++++++++++++++++++++++++++++
Follow my sketchbook adventures on

_nerdegade.com http://nerdegade.com/_+++++++++++++++++++++++++++++
