### ISSUE TITLE
add genyes logo to broswer tab

### ISSUE THREAD

**Issue by msyugovich** [AshotN/GenYesGHS#3]
![screen shot 2015-03-09 at 5 01 53 pm](https://cloud.githubusercontent.com/assets/11317976/6566992/122c375a-c67e-11e4-913c-7f7597fb3632.png)

Instead of a blank document icon, can you make the genyes logo appear? If not, what about a little square with the nice color gradient from the landing page?

**Comment by AshotN** [comment]
Has to be 32*32 so the GenYes Logo won't work... I put up a sample G

**Comment by msyugovich** [comment]
Please change the sample G to a Roboto or Arvo G

**Comment by msyugovich** [comment]
:)
